### ISSUE TITLE
Nuxt generate fails

### ISSUE THREAD

**Issue by tinus** [jmheretik/kirby-vue-starterkit#22]
Hi there, I am checking out the starter-kit and it looks very promising. I do get an error that I can't figure out.

Injecting into kirby works fine with npm run dev

building looks good but if I run generate I get:

`
FATAL  path.startsWith is not a function                                                                             20:00:34

  at Object.strip (utils/path.utils.js:3:14)
  at Object.toPageUri (utils/path.utils.js:9:34)
  at getPage (composables/use-kirby.js:27:42)
  at downloadImages (modules/kirby-scraper.js:24:24)
  at Array.map (<anonymous>)
  at modules/kirby-scraper.js:13:30
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:1021)
  at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:163:5)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:133:5)
  at async generate (node_modules/@nuxt/cli/dist/cli-generate.js:106:22)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:342:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2803:7)

`

I have no idea so any help would be greatly appreciated.

**Comment by jmheretik** [comment]
hi, thanks for noticing this, it was really stupid bug 😛

**Comment by tinus** [comment]
Hi, thanks for looking at this so quickly.

Idid get further now but am still running into an error:

`Entrypoint app = server.js server.js.map
i Kirby running at: http://127.0.0.1:8000                                                                             17:50:44
ℹ [HPM] Proxy created: **/*.json  -> http://127.0.0.1:8000                                                            17:50:44
ℹ [HPM] Proxy rewrite rule created: "/" ~> "/"                                                                        17:50:44
i Kirby running at: http://127.0.0.1:8000                                                                             17:50:44
ℹ Full static generation activated                                                                                    17:50:44

 FATAL  Request failed with status code 500                                                                           17:50:44

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
  at IncomingMessage.emit (events.js:327:22)
  at IncomingMessage.EventEmitter.emit (domain.js:467:12)
  at endReadableNT (internal/streams/readable.js:1327:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)

`
Should I disable injection for this to work?

**Comment by tinus** [comment]
The logfile
[2021-01-14T17_10_56_272Z-debug.log](https://github.com/jmheretik/kirby-vue-starterkit/files/5815919/2021-01-14T17_10_56_272Z-debug.log)

**Comment by jmheretik** [comment]
hmm, unfortunately i cant seem to replicate it and the logs also dont help :-/ i tried to run generate and it seems to work ok (btw the injection is not taken into account when you're generating since it doesnt make sense to inject static site to kirby)... but im on a windows machine, can you tell me all the settings that you changed?

**Comment by tinus** [comment]
I have done a clean git clone hoping that might help but sadly no luck.
Dev works, build works but generate fails sadly.

Just this mystery error.

Tinus Koorn
tinus@tick.nl
0644848775
tick.nl
